
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:19 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:19 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.3.1+2badb37d1 for .NET Framework
      生成启动时间为 2023/10/8 16:21:37。
      节点 1 上的项目“D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdC.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      VcpkgTripletSelection:
        Using triplet "x64-windows" from "D:\\vcpkg\\installed\\x64-windows\\"
        Using normalized configuration "Release"
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /I"D:\\vcpkg\\installed\\x64-windows\\include" /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:"D:\\vcpkg\\installed\\x64-windows\\lib" /LIBPATH:"D:\\vcpkg\\installed\\x64-windows\\lib\\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "D:\\vcpkg\\installed\\x64-windows\\lib\\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.exe
      AppLocalFromInstalled:
        pwsh.exe -ExecutionPolicy Bypass -noprofile -File "D:\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.exe" "D:\\vcpkg\\installed\\x64-windows\\bin" "Debug\\CompilerIdC.tlog\\CompilerIdC.write.1u.tlog" "Debug\\vcpkg.applocal.log"
        'pwsh.exe' 不是内部或外部命令，也不是可运行的程序
        或批处理文件。
        命令“pwsh.exe -ExecutionPolicy Bypass -noprofile -File "D:\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.exe" "D:\\vcpkg\\installed\\x64-windows\\bin" "Debug\\CompilerIdC.tlog\\CompilerIdC.write.1u.tlog" "Debug\\vcpkg.applocal.log"”已退出，代码为 9009。
        "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" -ExecutionPolicy Bypass -noprofile -File "D:\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.exe" "D:\\vcpkg\\installed\\x64-windows\\bin" "Debug\\CompilerIdC.tlog\\CompilerIdC.write.1u.tlog" "Debug\\vcpkg.applocal.log"
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate”执行 Touch 任务。
      已完成生成项目“D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:01.86
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        D:/SAN/计算机图形学/实验1.1/实验1.1_参考代码/CMakeFiles/3.27.4/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:19 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.3.1+2badb37d1 for .NET Framework
      生成启动时间为 2023/10/8 16:21:39。
      节点 1 上的项目“D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\3.27.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdCXX.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      VcpkgTripletSelection:
        Using triplet "x64-windows" from "D:\\vcpkg\\installed\\x64-windows\\"
        Using normalized configuration "Release"
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /I"D:\\vcpkg\\installed\\x64-windows\\include" /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:"D:\\vcpkg\\installed\\x64-windows\\lib" /LIBPATH:"D:\\vcpkg\\installed\\x64-windows\\lib\\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "D:\\vcpkg\\installed\\x64-windows\\lib\\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\3.27.4\\CompilerIdCXX\\CompilerIdCXX.exe
      AppLocalFromInstalled:
        pwsh.exe -ExecutionPolicy Bypass -noprofile -File "D:\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\3.27.4\\CompilerIdCXX\\CompilerIdCXX.exe" "D:\\vcpkg\\installed\\x64-windows\\bin" "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.write.1u.tlog" "Debug\\vcpkg.applocal.log"
        'pwsh.exe' 不是内部或外部命令，也不是可运行的程序
        或批处理文件。
        命令“pwsh.exe -ExecutionPolicy Bypass -noprofile -File "D:\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\3.27.4\\CompilerIdCXX\\CompilerIdCXX.exe" "D:\\vcpkg\\installed\\x64-windows\\bin" "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.write.1u.tlog" "Debug\\vcpkg.applocal.log"”已退出，代码为 9009。
        "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" -ExecutionPolicy Bypass -noprofile -File "D:\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\3.27.4\\CompilerIdCXX\\CompilerIdCXX.exe" "D:\\vcpkg\\installed\\x64-windows\\bin" "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.write.1u.tlog" "Debug\\vcpkg.applocal.log"
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
      已完成生成项目“D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\3.27.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:01.32
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/SAN/计算机图形学/实验1.1/实验1.1_参考代码/CMakeFiles/3.27.4/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:19 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/SAN/\u8ba1\u7b97\u673a\u56fe\u5f62\u5b66/\u5b9e\u9a8c1.1/\u5b9e\u9a8c1.1_\u53c2\u8003\u4ee3\u7801/CMakeFiles/CMakeScratch/TryCompile-t34w9v"
      binary: "D:/SAN/\u8ba1\u7b97\u673a\u56fe\u5f62\u5b66/\u5b9e\u9a8c1.1/\u5b9e\u9a8c1.1_\u53c2\u8003\u4ee3\u7801/CMakeFiles/CMakeScratch/TryCompile-t34w9v"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      VCPKG_APPLOCAL_DEPS: "ON"
      VCPKG_TARGET_TRIPLET: "x64-windows"
      Z_VCPKG_ROOT_DIR: "D:/vcpkg"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/SAN/计算机图形学/实验1.1/实验1.1_参考代码/CMakeFiles/CMakeScratch/TryCompile-t34w9v'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_732d2.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.3.1+2badb37d1 for .NET Framework
        生成启动时间为 2023/10/8 16:21:41。
        节点 1 上的项目“D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\CMakeScratch\\TryCompile-t34w9v\\cmTC_732d2.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_732d2.dir\\Debug\\”。
          正在创建目录“D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\CMakeScratch\\TryCompile-t34w9v\\Debug\\”。
          正在创建目录“cmTC_732d2.dir\\Debug\\cmTC_732d2.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_732d2.dir\\Debug\\cmTC_732d2.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_732d2.dir\\Debug\\\\" /Fd"cmTC_732d2.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.33.31629 版
          CMakeCCompilerABI.c
          版权所有(C) Microsoft Corporation。保留所有权利。
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_732d2.dir\\Debug\\\\" /Fd"cmTC_732d2.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\CMakeScratch\\TryCompile-t34w9v\\Debug\\cmTC_732d2.exe" /INCREMENTAL /ILK:"cmTC_732d2.dir\\Debug\\cmTC_732d2.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/SAN/计算机图形学/实验1.1/实验1.1_参考代码/CMakeFiles/CMakeScratch/TryCompile-t34w9v/Debug/cmTC_732d2.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/SAN/计算机图形学/实验1.1/实验1.1_参考代码/CMakeFiles/CMakeScratch/TryCompile-t34w9v/Debug/cmTC_732d2.lib" /MACHINE:X64  /machine:x64 cmTC_732d2.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_732d2.vcxproj -> D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\CMakeScratch\\TryCompile-t34w9v\\Debug\\cmTC_732d2.exe
        PostBuildEvent:
          setlocal
          C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -noprofile -executionpolicy Bypass -file D:/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary D:/SAN/计算机图形学/实验1.1/实验1.1_参考代码/CMakeFiles/CMakeScratch/TryCompile-t34w9v/Debug/cmTC_732d2.exe -installedDir D:/vcpkg/installed/x64-windows/debug/bin -OutVariable out
          if %errorlevel% neq 0 goto :cmEnd
          :cmEnd
          endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
          :cmErrorLevel
          exit /b %1
          :cmDone
          if %errorlevel% neq 0 goto :VCEnd
          :VCEnd
        FinalizeBuildStatus:
          正在删除文件“cmTC_732d2.dir\\Debug\\cmTC_732d2.tlog\\unsuccessfulbuild”。
          正在对“cmTC_732d2.dir\\Debug\\cmTC_732d2.tlog\\cmTC_732d2.lastbuildstate”执行 Touch 任务。
        已完成生成项目“D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\CMakeScratch\\TryCompile-t34w9v\\cmTC_732d2.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:01.26
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:19 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/SAN/\u8ba1\u7b97\u673a\u56fe\u5f62\u5b66/\u5b9e\u9a8c1.1/\u5b9e\u9a8c1.1_\u53c2\u8003\u4ee3\u7801/CMakeFiles/CMakeScratch/TryCompile-pp9u7d"
      binary: "D:/SAN/\u8ba1\u7b97\u673a\u56fe\u5f62\u5b66/\u5b9e\u9a8c1.1/\u5b9e\u9a8c1.1_\u53c2\u8003\u4ee3\u7801/CMakeFiles/CMakeScratch/TryCompile-pp9u7d"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      VCPKG_APPLOCAL_DEPS: "ON"
      VCPKG_TARGET_TRIPLET: "x64-windows"
      Z_VCPKG_ROOT_DIR: "D:/vcpkg"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/SAN/计算机图形学/实验1.1/实验1.1_参考代码/CMakeFiles/CMakeScratch/TryCompile-pp9u7d'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_a9fe2.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.3.1+2badb37d1 for .NET Framework
        生成启动时间为 2023/10/8 16:21:43。
        节点 1 上的项目“D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\CMakeScratch\\TryCompile-pp9u7d\\cmTC_a9fe2.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_a9fe2.dir\\Debug\\”。
          正在创建目录“D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\CMakeScratch\\TryCompile-pp9u7d\\Debug\\”。
          正在创建目录“cmTC_a9fe2.dir\\Debug\\cmTC_a9fe2.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_a9fe2.dir\\Debug\\cmTC_a9fe2.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_a9fe2.dir\\Debug\\\\" /Fd"cmTC_a9fe2.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.33.31629 版
          CMakeCXXCompilerABI.cpp
          版权所有(C) Microsoft Corporation。保留所有权利。
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_a9fe2.dir\\Debug\\\\" /Fd"cmTC_a9fe2.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\CMakeScratch\\TryCompile-pp9u7d\\Debug\\cmTC_a9fe2.exe" /INCREMENTAL /ILK:"cmTC_a9fe2.dir\\Debug\\cmTC_a9fe2.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/SAN/计算机图形学/实验1.1/实验1.1_参考代码/CMakeFiles/CMakeScratch/TryCompile-pp9u7d/Debug/cmTC_a9fe2.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/SAN/计算机图形学/实验1.1/实验1.1_参考代码/CMakeFiles/CMakeScratch/TryCompile-pp9u7d/Debug/cmTC_a9fe2.lib" /MACHINE:X64  /machine:x64 cmTC_a9fe2.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_a9fe2.vcxproj -> D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\CMakeScratch\\TryCompile-pp9u7d\\Debug\\cmTC_a9fe2.exe
        PostBuildEvent:
          setlocal
          C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -noprofile -executionpolicy Bypass -file D:/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary D:/SAN/计算机图形学/实验1.1/实验1.1_参考代码/CMakeFiles/CMakeScratch/TryCompile-pp9u7d/Debug/cmTC_a9fe2.exe -installedDir D:/vcpkg/installed/x64-windows/debug/bin -OutVariable out
          if %errorlevel% neq 0 goto :cmEnd
          :cmEnd
          endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
          :cmErrorLevel
          exit /b %1
          :cmDone
          if %errorlevel% neq 0 goto :VCEnd
          :VCEnd
        FinalizeBuildStatus:
          正在删除文件“cmTC_a9fe2.dir\\Debug\\cmTC_a9fe2.tlog\\unsuccessfulbuild”。
          正在对“cmTC_a9fe2.dir\\Debug\\cmTC_a9fe2.tlog\\cmTC_a9fe2.lastbuildstate”执行 Touch 任务。
        已完成生成项目“D:\\SAN\\计算机图形学\\实验1.1\\实验1.1_参考代码\\CMakeFiles\\CMakeScratch\\TryCompile-pp9u7d\\cmTC_a9fe2.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:01.26
        
      exitCode: 0
...
